version: '3.8'

services:
  client:
    container_name: react-client
    build:
      context: ./@apps/client
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
    ports:
      - '5173:5173'
    depends_on:
      - server

  server:
    container_name: express-server
    build:
      context: ./@apps/server
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
