version: '3.8'

services:
  client:
    container_name: react-client
    build:
      context: .
      dockerfile: ./@apps/client/Dockerfile.client
    volumes:
      - .:/app
      - '/app/@apps/client/node_modules'
    ports:
      - '5173:5173'
    depends_on:
      - server
    stdin_open: true

  server:
    container_name: express-server
    build:
      context: .
      dockerfile: ./@apps/server/Dockerfile.server
    volumes:
      - .:/app
      - '/app/@apps/server/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data:
